# Generated by Django 5.2.3 on 2025-07-04 08:06

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Transducer",
            fields=[
                ("row_index", models.IntegerField(primary_key=True, serialize=False)),
                ("model_name", models.TextField()),
                ("manufacturer", models.TextField()),
                ("rcx0", models.IntegerField()),
                ("rcy0", models.IntegerField()),
                ("rcx1", models.IntegerField()),
                ("rcy1", models.IntegerField()),
                ("phys_units_x", models.IntegerField()),
                ("phys_units_y", models.IntegerField()),
                ("phys_delta_x", models.FloatField()),
                ("phys_delta_y", models.FloatField()),
                ("transducer_name", models.TextField()),
            ],
            options={
                "db_table": "transducers",
            },
        ),
        migrations.CreateModel(
            name="Ultrasound",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("contentdate", models.CharField(max_length=32)),
                ("contenttime", models.CharField(max_length=32)),
                ("deviceserialnumber", models.CharField(max_length=64)),
                ("instancenumber", models.CharField(max_length=64)),
                ("institutionname", models.CharField(max_length=255)),
                ("institutionaldepartmentname", models.CharField(max_length=255)),
                ("manufacturer", models.CharField(max_length=255)),
                ("manufacturermodelname", models.CharField(max_length=255)),
                ("modality", models.CharField(max_length=64)),
                ("patientid", models.CharField(max_length=64)),
                ("patientname", models.CharField(max_length=255)),
                ("sopclassuid", models.CharField(max_length=64)),
                ("sopinstanceuid", models.CharField(max_length=64)),
                ("seriesdate", models.CharField(max_length=32)),
                ("seriesinstanceuid", models.CharField(max_length=64)),
                ("seriesnumber", models.CharField(max_length=64)),
                ("seriestime", models.CharField(max_length=32)),
                ("stationname", models.CharField(max_length=255)),
                ("studydate", models.CharField(max_length=32)),
                ("studyid", models.CharField(max_length=64)),
                ("instance", models.CharField(max_length=64)),
                ("studytime", models.CharField(max_length=32)),
                ("tranducertype", models.CharField(max_length=255)),
                ("serie", models.CharField(max_length=255)),
                ("s_depth", models.FloatField()),
                ("u_cov", models.FloatField()),
                ("u_skew", models.FloatField()),
                ("u_low", models.JSONField(blank=True, null=True)),
                ("horiz_prof", models.JSONField(blank=True, null=True)),
                ("vert_prof", models.JSONField(blank=True, null=True)),
            ],
            options={
                "db_table": "ultrasound",
            },
        ),
    ]
