# Generated by Django 5.2.8 on 2026-02-18 13:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('first_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='xrayanalysis',
            name='contrast_rois_image',
            field=models.BinaryField(blank=True, help_text='ROI-kartta PNG (uniformity + kontrasti)', null=True),
        ),
        migrations.AddField(
            model_name='xrayanalysis',
            name='cu_000_std',
            field=models.FloatField(blank=True, help_text='Cu 0.0mm hajonta', null=True),
        ),
        migrations.AddField(
            model_name='xrayanalysis',
            name='cu_030_std',
            field=models.FloatField(blank=True, help_text='Cu 0.3mm hajonta', null=True),
        ),
        migrations.AddField(
            model_name='xrayanalysis',
            name='cu_065_std',
            field=models.FloatField(blank=True, help_text='Cu 0.65mm hajonta', null=True),
        ),
        migrations.AddField(
            model_name='xrayanalysis',
            name='cu_100_std',
            field=models.FloatField(blank=True, help_text='Cu 1.0mm hajonta', null=True),
        ),
        migrations.AddField(
            model_name='xrayanalysis',
            name='cu_140_std',
            field=models.FloatField(blank=True, help_text='Cu 1.4mm hajonta', null=True),
        ),
        migrations.AddField(
            model_name='xrayanalysis',
            name='cu_185_std',
            field=models.FloatField(blank=True, help_text='Cu 1.85mm hajonta', null=True),
        ),
        migrations.AddField(
            model_name='xrayanalysis',
            name='cu_230_std',
            field=models.FloatField(blank=True, help_text='Cu 2.3mm hajonta', null=True),
        ),
        migrations.AddField(
            model_name='xrayanalysis',
            name='distance_source_to_detector',
            field=models.TextField(blank=True, help_text='Lähde-detektori etäisyys (mm)'),
        ),
        migrations.AddField(
            model_name='xrayanalysis',
            name='exposure_mAs',
            field=models.TextField(blank=True, help_text='Kokonaisvalotus (mAs)'),
        ),
        migrations.AddField(
            model_name='xrayanalysis',
            name='focal_spot',
            field=models.TextField(blank=True, help_text='Fokuskoko'),
        ),
        migrations.AddField(
            model_name='xrayanalysis',
            name='low_contrast_details',
            field=models.JSONField(blank=True, help_text='LC ROI:den yksityiskohdat (kontrasti, CNR, näkyvyys per ROI)', null=True),
        ),
        migrations.AddField(
            model_name='xrayanalysis',
            name='mtf_curve_image',
            field=models.BinaryField(blank=True, help_text='MTF-analyysi PNG (viivapari-ROI:t + käyrä)', null=True),
        ),
        migrations.AddField(
            model_name='xrayanalysis',
            name='protocol_name',
            field=models.TextField(blank=True, help_text='Kuvausprotokolla'),
        ),
    ]
