# Generated by Django 5.2.8 on 2026-02-20 12:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('first_app', '0003_ctanalysis'),
    ]

    operations = [
        migrations.AddField(
            model_name='ctanalysis',
            name='hu_linearity_chart_image',
            field=models.BinaryField(blank=True, help_text='HU-lineaarisuus scatter plot PNG', null=True),
        ),
        migrations.AddField(
            model_name='ctanalysis',
            name='mtf_chart_image',
            field=models.BinaryField(blank=True, help_text='MTF-käyrä PNG', null=True),
        ),
        migrations.AddField(
            model_name='ctanalysis',
            name='side_view_image',
            field=models.BinaryField(blank=True, help_text='Sivunäkymä PNG', null=True),
        ),
        migrations.AddField(
            model_name='ctanalysis',
            name='uniformity_profile_image',
            field=models.BinaryField(blank=True, help_text='Uniformiteettiprofiilit PNG', null=True),
        ),
        migrations.AlterField(
            model_name='ctanalysis',
            name='hu_linearity_image',
            field=models.BinaryField(blank=True, help_text='CTP404 leikekuva PNG', null=True),
        ),
        migrations.AlterField(
            model_name='ctanalysis',
            name='low_contrast_image',
            field=models.BinaryField(blank=True, help_text='CTP515 leikekuva PNG', null=True),
        ),
        migrations.AlterField(
            model_name='ctanalysis',
            name='mtf_image',
            field=models.BinaryField(blank=True, help_text='CTP528 leikekuva PNG', null=True),
        ),
        migrations.AlterField(
            model_name='ctanalysis',
            name='summary_image',
            field=models.BinaryField(blank=True, help_text='Yhteenvetokuva PNG (ei käytössä)', null=True),
        ),
        migrations.AlterField(
            model_name='ctanalysis',
            name='uniformity_image',
            field=models.BinaryField(blank=True, help_text='CTP486 leikekuva PNG', null=True),
        ),
    ]
