# Generated by Django 5.2.8 on 2026-02-23 13:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('first_app', '0004_ctanalysis_hu_linearity_chart_image_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='xrayanalysis',
            name='mtf_lp_image',
            field=models.BinaryField(blank=True, help_text='MTF-viivapari kuva PNG', null=True),
        ),
        migrations.AlterField(
            model_name='xrayanalysis',
            name='contrast_rois_image',
            field=models.BinaryField(blank=True, help_text='ROI-kartta PNG (tumma, kaikki ROI:t)', null=True),
        ),
        migrations.AlterField(
            model_name='xrayanalysis',
            name='mtf_curve_image',
            field=models.BinaryField(blank=True, help_text='MTF-käyrä PNG (dark-teema)', null=True),
        ),
    ]
