# Generated by Django 5.2.8 on 2026-02-24 07:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('first_app', '0005_xrayanalysis_mtf_lp_image_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='ctanalysis',
            name='thickness_image',
            field=models.BinaryField(blank=True, help_text='CTP404 leikekuva PNG (vain leikepaksuus-ramppi-ROI:t)', null=True),
        ),
        migrations.AlterField(
            model_name='ctanalysis',
            name='hu_linearity_image',
            field=models.BinaryField(blank=True, help_text='CTP404 leikekuva PNG (vain HU materiaali-ROI:t)', null=True),
        ),
    ]
