# Generated by Django 5.2.8 on 2026-03-09 10:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PlatformService',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('description', models.CharField(blank=True, max_length=255)),
                ('container', models.CharField(blank=True, help_text='Docker-kontin nimi', max_length=100)),
                ('host', models.CharField(blank=True, help_text='Docker-verkon sisäinen nimi', max_length=100)),
                ('port', models.IntegerField(default=0, help_text='Palvelun sisäinen portti')),
                ('host_port', models.IntegerField(default=0, help_text='Host-portti (Windows localhost)')),
                ('category', models.CharField(choices=[('infrastructure', 'Infrastruktuuri'), ('microservice', 'Mikropalvelu'), ('application', 'Sovellus'), ('platform', 'Platform'), ('monitoring', 'Monitorointi'), ('external', 'Ulkoinen')], default='microservice', max_length=20)),
                ('layer', models.CharField(choices=[('orchestration', 'Orchestration & Monitoring'), ('reception', 'Data Reception'), ('persistence', 'Data Persistence'), ('processing', 'Data Processing'), ('presentation', 'Presentation'), ('monitoring', 'Monitoring'), ('external', 'External')], default='processing', max_length=20)),
                ('url', models.URLField(blank=True, help_text='Selaimen osoite (valinnainen)')),
                ('pos_x', models.FloatField(default=100)),
                ('pos_y', models.FloatField(default=100)),
                ('is_active', models.BooleanField(default=True, help_text='Näytetäänkö kaaviossa')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'platform_services',
                'ordering': ['category', 'name'],
            },
        ),
        migrations.CreateModel(
            name='PlatformConnection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('protocol', models.CharField(choices=[('gRPC', 'gRPC'), ('REST API', 'REST API'), ('SQL', 'SQL'), ('HTTP', 'HTTP'), ('DICOM', 'DICOM C-STORE'), ('TCP', 'TCP')], default='HTTP', max_length=20)),
                ('label', models.CharField(blank=True, max_length=100)),
                ('from_service', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='connections_out', to='platform_app.platformservice')),
                ('to_service', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='connections_in', to='platform_app.platformservice')),
            ],
            options={
                'db_table': 'platform_connections',
                'unique_together': {('from_service', 'to_service', 'protocol')},
            },
        ),
    ]
