# Generated by Django 5.2.8 on 2026-03-09 11:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('platform_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('description', models.CharField(blank=True, max_length=500)),
                ('is_default', models.BooleanField(default=False, help_text='Oletusnäkymä (Dashboard)')),
                ('svg_width', models.IntegerField(default=1100)),
                ('svg_height', models.IntegerField(default=560)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'platform_projects',
                'ordering': ['-is_default', 'name'],
            },
        ),
        migrations.AlterField(
            model_name='platformservice',
            name='name',
            field=models.CharField(max_length=100),
        ),
        migrations.AddField(
            model_name='platformconnection',
            name='project',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='connections', to='platform_app.project'),
        ),
        migrations.AddField(
            model_name='platformservice',
            name='project',
            field=models.ForeignKey(blank=True, help_text='Projekti johon palvelu kuuluu', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='services', to='platform_app.project'),
        ),
        migrations.AlterUniqueTogether(
            name='platformservice',
            unique_together={('project', 'name')},
        ),
        migrations.CreateModel(
            name='ProjectLayer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Tekninen nimi', max_length=50)),
                ('label', models.CharField(help_text='Näytettävä otsikko', max_length=100)),
                ('order', models.IntegerField(default=0, help_text='Järjestys ylhäältä alas')),
                ('y_position', models.FloatField(default=0, help_text='SVG y-koordinaatti')),
                ('height', models.FloatField(default=100, help_text='SVG korkeus')),
                ('color', models.CharField(blank=True, help_text='Taustaväri (valinnainen)', max_length=30)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='layers', to='platform_app.project')),
            ],
            options={
                'db_table': 'platform_layers',
                'ordering': ['project', 'order'],
                'unique_together': {('project', 'name')},
            },
        ),
        migrations.AddField(
            model_name='platformservice',
            name='layer_ref',
            field=models.ForeignKey(blank=True, help_text='Viittaus projektin layeriin', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='services', to='platform_app.projectlayer'),
        ),
    ]
